pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                sh 'cd SimpleMockito'
                sh 'gradlew test'
                junit '**/build/**/*.xml'
            }
        }
    }
}
