pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                dir("${env.WORKSPACE}/SimpleMockito") {
                    sh 'pwd'
                    sh './gradlew test'
                    junit '**/build/**/*.xml'
                }
            }
        }
    }
}
